name: Release with Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Build the binary for ${{ matrix.os }}
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            go build -o enumerator.exe
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            go build -o enumerator
          else
            go build -o enumerator
          fi

      - name: Move the binary files
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv enumerator.exe enumerator-windows.exe
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv enumerator enumerator-darwin
          else
            mv enumerator enumerator-linux
          fi

      - name: Archive the binaries
        run: |
          mkdir release
          mv enumerator-linux release/
          mv enumerator-windows.exe release/
          mv enumerator-darwin release/
          cd release
          zip -r release-binaries.zip *

      - name: Upload release to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: release/release-binaries.zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
