name: Release with Source Archive

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Archive entire source
        run: |
          git archive --format=zip -o source.zip HEAD
          git archive --format=tar.gz -o source.tar.gz HEAD

      - name: Upload release to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            source.zip
            source.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
